### ISSUE TITLE
[Feature Request] Other database backends

### ISSUE THREAD

**Issue by cittyinthecloud** [billwi/CyberTigerScoreboard#2]
@billwi ,
After seeing a scoring engine at https://samsclass.info/140/proj/CP-LSE.htm that mentioned your username on GitHub that mentioned your previous projects, I got curious and checked out your github page.
I'm a newer (2nd year) CyberPatriot competitor, and have been writing a scoring engine, but I don't have good access to Azure because school filters.

The ability to use other backends, even just MySQL for this project would be useful for a lot of smaller CyberPatriot teams.

After I brush up on Java a bit I might submit a pull request and add this myself if your fine with that.

Thanks,
@famous1622

**Comment by cool00geek** [comment]
Hi, and thanks for your interest! 

for one, an Azure database is nothing but a Microsoft SQL server hosted on their Azure platform. if you can install and get that server running on a computer on your school's lan, or a personal server, that would work as well. 

My question for you is what scoring engine are you working on? If it's for Linux, please let me know where my engine falls short as it would be beneficial for you to avoid writing another engine. If you are writing one for Windows, I would have some use for it, so do share it when you finish.

If you still would prefer an SQL option in this scoreboard and the engine you found on that website (also made by me), please send me the SQL commands for adding data to a database and retrieving data as well, as I am not familiar with mySQL.

**Comment by cittyinthecloud** [comment]
Wow, thanks for the quick response

Mostly my issue with the engine I found was that there were a few issues with auto checking of vulns, and SQL support. I'd like to use MySQL as my school is having a Linux "server" setup just for our CyberPatriot (no more copying 4GB files off of flash drives) and I'd like to use that. Also our filter doesn't like Azure. 

For Windows, I have been writing a python thing that parses the score and other thing and throws it out to the console, but I wouldn't mind writing some code to push it over SQL.

If I have my github markdown-fu remembered, here are the commands for SQL Data transferring in MySQL, but they should look similar to MS's.

Select all from table:
```sql
SELECT * FROM table_name;
```
Select columns from table:
```sql
SELECT column1, column2, ... FROM table_name; 
```
Select where:
```sql
SELECT column1, column2, ... FROM table_name WHERE condition;
```
Insert into:
```sql
INSERT INTO table_name (column1, column2, column3, ...) VALUES (value1, value2, value3, ...)
```
or for all columns
```sql
INSERT INTO table_name VALUES (value1, value2, value3, ...); 
```

Sorry about the massive set of sql commands being most of this

**Comment by cool00geek** [comment]
So to clarify, you want the MySQL functionality on both the engine and the graph, correct?

You also said that there were some issues with the autochecking of vulns, can you clarify that? 

I'll start working on it as soon as I can, but if you can work on it and create a pull request that would be great!

**Comment by cittyinthecloud** [comment]
Both yes, I'll work on MySQL for the scoreboard, but it'd really be nice for the engine. Thanks :)
And for the autochecking, on 16.04 it sometimes wouldn't manage to catch a command, but that might of been the amount of crap that I did to that image, cause I just tested and it works fine, sorry about that :P

**Comment by cool00geek** [comment]
No worries :)

I am currently really busy so I can't give you an ETA, but I will work on it when I get a chance.

**Comment by cittyinthecloud** [comment]
I got the scoreboard forked to famous1622/CyberTigerScoreboard and working on it now :)

**Comment by cittyinthecloud** [comment]
PR billwi/CyberTigerScoreboard#3

**Comment by cool00geek** [comment]
I finally had some time to work on it (Sorry over 1 month after the request), but I do have the code that should theoretically work to upload the score to a MySQL database, just like how it works in a Microsoft database. I will be able to update the jar on the website you linked earlier once I get this tested. Thanks for your patience @famous1622!

**Comment by cittyinthecloud** [comment]
No problem, and thank you for the scoreboard and engine :)

I found a problem with the UI of the engine being unscalable. This makes them difficuklt to uses on school laptops with 1366x768 monitors, but this isn't a huge problem, especially considering alot of the ui seems to be hardcoded

Thanks for the response,
@famous1622

**Comment by cool00geek** [comment]
Wow you still use 1366x768! I'll try and make it more adaptive to that resolution then.

**Comment by cittyinthecloud** [comment]
Yeah, Dell makes weird laptops, because the graphics card can do MUCH more :P

**Comment by cittyinthecloud** [comment]
Is there a more appropriate way to contact over the other program than this issue thread. Maybe discord pms?

**Comment by cool00geek** [comment]
I don't use discord, but you can contact me on Google hangouts on my Github email (cool00geek [at] yahoo.com)

**Comment by cool00geek** [comment]
PR #3 has been merged.
